prefix: "&8[&bPvP&9System&8]&7: &f"

# In Ticks
joinMessageDuration: 100

damageThreshold: 6
damageBelowThreshold: 1
lastDamageDuration: 2000

peacefulCommandCooldownAfterPvp: 60000

damageEntryButtons:
  replay:
    displayCondition: "HAS_TRIGGER"
    display: "&d[Replay]&7 "
    hover: "&eClick&7 to watch the recorded replay.\n&8May fail if the replay is invalid."
    command: "replay play %triggerKey%"

deathEntryButtons:
  openinv:
    displayCondition: "ALL"
    display: " &c[OpenInv]&7"
    hover: "&eClick&7 to view the player's current inventory."
    command: "openinv %uuid%"
  replay:
    displayCondition: "HAS_TRIGGER"
    display: " &d[Replay]&7"
    hover: "&eClick&7 to watch the recorded replay.\n&8May fail if the replay is invalid."
    command: "replay play %triggerKey%"

actionTrigger:
  enabled: true
  activateCommands:
    - "advancedreplay:replay start %triggerKey%"
  delaySinceLastEvent: 15000
  deactivateCommands:
    - "advancedreplay:replay stop %triggerKey%"

lang:
  commands:
    noPermission: "&cYou don't have permission to use this command."
    noPlayer: "&cOnly players can use this command."
    invalidCommand: "&cUsage: &e%command%"
    notAPlayer: "&cNo player found with name &e%name%&c."

    peaceful:
      setOn: "&7Peaceful mode: &aenabled&7."
      setOff: "&7Peaceful mode: &cdisabled&7."
      setOnOther: "&7Peaceful mode for &e%player%&7: &aenabled&7."
      setOffOther: "&7Peaceful mode for &e%player%&7: &cdisabled&7."
      alreadyOn: "&7Peaceful mode is already &aenabled&7."
      alreadyOff: "&7Peaceful mode is already &cdisabled&7."
      alreadyOnOther: "&7Peaceful mode for &e%player%&7 is already &aenabled&7."
      alreadyOffOther: "&7Peaceful mode for &e%player%&7 is already &cdisabled&7."
      onByOther: "&7Peaceful mode was &aenabled&7 by &e%from%&7."
      offByOther: "&7Peaceful mode was &cdisabled&7 by &e%from%&7."
      cooldown: "&cYou can't enable Peaceful mode while in PvP cooldown."

    lookup:
      filterError: "&cError parsing filter: &e%error%"
      noEntries: "&cNo entries match your query."

      ui:
        header: "&8-----&8[ &aLookup Results &7(&e%entries%&7) &8]-----"

        entry:
          deathLine: "%timestamp% &c☠ &e%defender%&7 was slain by &e%attacker%&7 %pos% %info%"
          damageLine: "%timestamp% &6⚔ &e%defender%&7 was hit by &e%attacker%&7 %pos% %info%"

          timestamp: "&8[&7dd.MM HH:mm&8]"
          pos: "&e[Pos]"
          posHover: "&eClick&7 to teleport.\n&8%world% &7(&e%x%&7, &e%y%&7, &e%z%&7)"
          info: "&b[Info]"
          damageInfoHover: "&eDamage Details:\n&7Time: &f%timestamp%\n&7Victim: &e%defender% &7(&a%defenderHealth%❤&7)\n&7Attacker: &e%attacker% &7(&a%attackerHealth%❤&7)\n&7Cause: &f%cause%\n&7Location: &8%world% &7(&e%x%&7, &e%y%&7, &e%z%&7)\n&7Damage: &c%damage%\n&7Original: &c%originalDamage%\n&7Trigger: &e%triggerKey%\n\n&8Click for actions."
          deathInfoHover: "&eDeath Details:\n&7Time: &f%timestamp%\n&7Victim: &e%defender%\n&7Attacker: &e%attacker% &7(&a%attackerHealth%❤&7)\n&7Cause: &f%cause%\n&7Location: &8%world% &7(&e%x%&7, &e%y%&7, &e%z%&7)\n&7Levels lost: &a%levels%\n&7Items in inv: &e%itemsInInv%\n&7Trigger: &e%triggerKey%\n\n&8Click for actions."
          teleportSuccess: "&aTeleported&7. &eClick&7 to return to survival."
          teleportHover: "&eClick&7 to return to survival."

          mode:
            peaceful: "&a"
            violent: "&c"
            non: "&7"

        page:
          template: "&8Page: &e%current%&8/&7%max%  %prev%&8%pages% %next%"
          prev: "&7◀ "
          next: "&7▶"
          selectedPage: "&e&l%page%"
          otherPage: "&7%page%"
          separator: "&8 | "

        info:
          damageInfo: "&8&m-----&8[ &eDamage Info &7- &e%defender% &7(&a%defenderHealth%❤&7) &8]&m-----\n&7Time: &f%timestamp%\n&7Attacker: &e%attacker% &7(&a%attackerHealth%❤&7)\n&7Location: &8%world% &7(&e%x%&7, &e%y%&7, &e%z%&7)\n&7Cause: &f%cause%\n&7Damage: &c%originalDamage% &7→ &c%damage%"
          deathInfo: "&8&m-----&8[ &cDeath Info &7- &e%defender% &7(&a%defenderHealth%❤&7) &8]&m-----\n&7Time: &f%timestamp%\n&7Attacker: &e%attacker% &7(&a%attackerHealth%❤&7)\n&7Location: &8%world% &7(&e%x%&7, &e%y%&7, &e%z%&7)\n&7Cause: &f%cause%\n&7Levels lost: &a%levels%  &7Itemstacks: &e%itemsInInv%"
          viewButton: "&a[View]&7 "
          viewHover: "&eClick&7 to view the inventory."
          resetButton: "&c[Reset]&7"
          resetHover: "&eClick&7 to reset the inventory.\n&4This replaces the current inventory!"

        inventoryTitle: "&8Death Inventory &7- &e%player%"
        playerNotOnline: "&cThe player must be online to reset the inventory."

  join:
    message:
      peaceful: "&7Mode: &aPeaceful"
      notPeaceful: "&7Mode: &cPvP Enabled"

  # Placeholders: %attacker%, %defender%
  damage:
    message:
      attacker:
        isPeaceful: "&cYou're in &aPeaceful&c mode. Don't attack players!"
        isNotPeaceful: "&eWarning:&7 Your opponent is in &aPeaceful&7 mode. Attacking may be punished."

      defender:
        isPeaceful: "&e%attacker%&c is attacking you &7while you're in &aPeaceful&7 mode!"
        isNotPeaceful: "&7You're protected because the other player is in &aPeaceful&7 mode."

  # Placeholders: %attacker%, %defender%
  death:
    message:
      attacker:
        isPeaceful: "&cYou killed a player while in &aPeaceful&c mode. This may be punished!"
        isNotPeaceful: "&eWarning:&7 You killed a player in &aPeaceful&7 mode. This may be punished!"

      defender:
        isPeaceful: "&cYou died while in &aPeaceful&c mode. Report &e%attacker%&c if this was unfair."
        isNotPeaceful: "&cYou were killed by a player in &aPeaceful&c mode. You can report &e%attacker%&c."
